### ISSUE TITLE
Kubernetes: Container won't start: sshd returned with state 1

### ISSUE THREAD

**Issue by nastye** [exasol/docker-db#47]
We've been running an exasol container as a simple deployment, but since cluster restart, the container doesn't finish initialization anymore.

Kubernetes 1.16.7 (AKS)
deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v7-exasol
  labels:
    v7.service: v7-exasol
spec:
  selector:
    matchLabels:
      v7.service: v7-exasol
  template:
    metadata:
      name: v7-exasol
      labels:
        v7.service: v7-exasol
    spec:
      containers:
        - name: exasol
          image: exasol/docker-db:6.2.6-d1
          ports:
          - containerPort: 8888
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 2Gi
          env:
          - name: EXA_NODE_IP_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          volumeMounts:
          - name: exa
            mountPath: /exa
            readOnly: false
      volumes:
        # exasol data volume
        - name: exa
          persistentVolumeClaim:
            claimName: v7-exasol-claim
```
Container output:
[exa.log](https://github.com/exasol/docker-db/files/4649685/exa.log)
Manually starting sshd with commandline found in exainit/tasks/services.py:
```
[root@n11 /]# /usr/sbin/sshd -D -o PermitRootLogin=yes -o MaxStartups=300:30:800 -h /exa/etc/hostkey -p 22
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0777 for '/exa/etc/hostkey' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
key_load_private: bad permissions
Could not load host key: /exa/etc/hostkey
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
sshd: no hostkeys available -- exiting.
```
Clearly, the permissions are not what they should be, and comparing to a working container, they are not.
```
-rwxrwxrwx 1 root root 1675 May 19 10:51 hostkey
vs
-rw------- 1 root      root      1679 May 13 08:57 hostkey
```
However, the file permissions can't be fixed through chmod'ing.
