### ISSUE TITLE
Add latest tag to latest 6.0

### ISSUE THREAD

**Issue by theory** [exasol/docker-db#69]
Would it be possible to add a `latest-6.0` tag to the latest 6.0 release, presumably [6.0.16-d1](https://hub.docker.com/layers/exasol/docker-db/6.0.16-d1/images/sha256-8d302868652f444faba5db535c01a7835fe3f5a2a64102625b416d167a40a5da?context=explore)? Would simplify configuration for those of us who do matrix testing over several versions. An example GitHub action configuration:

``` yaml
jobs:
  Exasol:
    # Run only on develop or main, or when a pg file has changed in the branch.
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || ${{ needs.filter.outputs.exasol == 'true' }}
    strategy:
      matrix:
        exasol: ['7.1', '7.0', '6.2', '6.1', '6.0']
    name: Exasol ${{ matrix.exasol }}
    runs-on: ubuntu-latest
    services:
      exasol:
        image: exasol/docker-db:latest-${{ matrix.exasol }}
        ports: [ 8888 ]
```

Note the scond-to-last line won't work for 6.0, since the `latest-6.0` tag does not exist.

Thanks!
